# -*- coding: utf-8 -*-
"""TechTheoryLab_VoiceStudio_Pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yT0ewXpUW48k2vSmjCcfEGw-UHgGqtXy
"""

# --- CELL 1: MOUNT DRIVE & INSTALL DEPENDENCIES ---

# 1. Connect to Google Drive
from google.colab import drive
print("Mounting Google Drive...")
drive.mount('/content/drive')

# 2. Install required libraries
print("Installing dependencies...")
pip install -q torch soundfile gradio transformers accelerate qwen_tts

print("✅ Drive mounted and dependencies installed! Move on to Cell 2.")

# --- CELL 2: INSTALL AUDIO & TRANSLATION TOOLS ---

print("Installing additional audio tools and translators...")
!pip install -q librosa openai-whisper deep-translator

print("Installing system audio libraries (SoX & FFmpeg for format conversion)...")
!apt-get update && apt-get install -y sox libsox-fmt-all ffmpeg

print("✅ All audio dependencies installed successfully! Move on to Cell 3.")

# --- CELL 3: THE ULTIMATE QWEN3-TTS STUDIO (TECH THEORY LAB EDITION) ---
import os
import sys
import json
import torch
import soundfile as sf
import gradio as gr
from qwen_tts import Qwen3TTSModel
import shutil
import datetime
import re
import numpy as np
import librosa
import whisper
import gc
from deep_translator import GoogleTranslator

# =========================================================================
# 🕵️ SMART ENVIRONMENT DETECTOR (Colab vs Local PC)
# =========================================================================
IS_COLAB = 'google.colab' in sys.modules or os.path.exists('/content')

# =========================================================================
# ⚙️ MAIN SETTINGS (Only matters if running inside Google Colab)
# =========================================================================
SAVE_MODELS_TO_DRIVE = False
# =========================================================================

# Folder paths setup based on environment
if IS_COLAB:
    print("🌐 Environment Detected: Google Colab")
    if SAVE_MODELS_TO_DRIVE:
        os.environ["HF_HOME"] = "/content/drive/MyDrive/Ai/qwen_models"
        print("💾 Models will be cached in Google Drive.")
    else:
        os.environ.pop("HF_HOME", None)
        print("☁️ Models will be stored temporarily in Colab Storage.")

    base_output_path = "/content/drive/MyDrive/Ai/output/voice"
else:
    print("💻 Environment Detected: Local PC / Hugging Face Spaces")
    os.environ.pop("HF_HOME", None)
    base_output_path = "./TechTheoryLab_Output/voice"

voice_folder = base_output_path
os.makedirs(voice_folder, exist_ok=True)

presets_master_folder = os.path.join(voice_folder, "Presets")
os.makedirs(presets_master_folder, exist_ok=True)

presets_file = os.path.join(presets_master_folder, "voice_presets.json")
clone_presets_file = os.path.join(presets_master_folder, "clone_presets.json")
clone_audio_folder = os.path.join(presets_master_folder, "clone_audio")
os.makedirs(clone_audio_folder, exist_ok=True)

# =========================================================================
# 🧠 VRAM AUTO-SWAPPER & MODELS
# =========================================================================
model_base = None
model_design = None
current_model_loaded = None

def manual_clear_vram():
    global model_base, model_design, current_model_loaded
    if model_base is not None:
        del model_base
        model_base = None
    if model_design is not None:
        del model_design
        model_design = None
    current_model_loaded = None
    gc.collect()
    torch.cuda.empty_cache()
    return "🧹 GPU Memory Cleared! Ready to load fresh models."

def switch_vram_model(target):
    global model_base, model_design, current_model_loaded
    if current_model_loaded == target: return

    print(f"🔄 VRAM Manager: Offloading previous model and loading Qwen3 {target.upper()}...")

    if target == "base":
        if model_design is not None:
            del model_design
            model_design = None
        gc.collect()
        torch.cuda.empty_cache()
        model_base = Qwen3TTSModel.from_pretrained("Qwen/Qwen3-TTS-12Hz-1.7B-Base", device_map="cuda:0", dtype=torch.bfloat16, attn_implementation="sdpa")

    elif target == "design":
        if model_base is not None:
            del model_base
            model_base = None
        gc.collect()
        torch.cuda.empty_cache()
        model_design = Qwen3TTSModel.from_pretrained("Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign", device_map="cuda:0", dtype=torch.bfloat16, attn_implementation="sdpa")

    current_model_loaded = target
    print("✅ VRAM Manager: Model switched successfully.")

switch_vram_model("design")

print("Loading Whisper for Subtitles...")
device = "cuda" if torch.cuda.is_available() else "cpu"
whisper_model = whisper.load_model("base", device=device)

# =========================================================================
# 🛠️ HELPER FUNCTIONS
# =========================================================================
QWEN_LANGUAGES = ["Auto", "English", "Chinese", "Japanese", "Korean", "French", "German", "Spanish"]

def split_text_into_chunks(text):
    text = text.replace('\n', ' ')
    sentences = re.split(r'(?<!\bMr)(?<!\bMrs)(?<!\bDr)(?<!\be\.g)(?<!\bi\.e)(?<=[.!?]) +', text)
    valid_chunks = []
    for s in sentences:
        s = s.strip()
        if len(s) > 0:
            if not s[-1] in ".!?": s += "."
            valid_chunks.append(s)
    return valid_chunks

def format_timestamp(seconds):
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    millisecs = int((seconds - int(seconds)) * 1000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millisecs:03d}"

def write_srt_file(segments, file_path):
    with open(file_path, "w", encoding="utf-8") as f:
        for i, segment in enumerate(segments):
            start = format_timestamp(segment['start'])
            end = format_timestamp(segment['end'])
            text = segment['text'].strip()
            f.write(f"{i+1}\n{start} --> {end}\n{text}\n\n")

def mix_background_music(voice_y, voice_sr, bgm_path, bgm_vol):
    bgm_y, bgm_sr = librosa.load(bgm_path, sr=voice_sr)
    if len(bgm_y) < len(voice_y):
        repeats = int(np.ceil(len(voice_y) / len(bgm_y)))
        bgm_y = np.tile(bgm_y, repeats)
    bgm_y = bgm_y[:len(voice_y)]
    mixed = voice_y + (bgm_y * bgm_vol)
    max_amp = np.max(np.abs(mixed))
    if max_amp > 1.0:
        mixed = mixed / max_amp * 0.95
    return mixed

def convert_audio_format(wav_file, target_format):
    target_format = target_format.lower().strip()
    if target_format == "wav":
        return wav_file
    out_file = wav_file.rsplit('.', 1)[0] + f".{target_format}"
    os.system(f"ffmpeg -y -i '{wav_file}' -q:a 0 '{out_file}' -loglevel error")
    if os.path.exists(wav_file) and os.path.exists(out_file):
        os.remove(wav_file)
    return out_file

def process_audio_studio(audio_path, do_norm, do_trim, speed, do_srt, bgm_path, bgm_vol, out_format="WAV", progress=gr.Progress()):
    if not audio_path: return None, None, "⚠️ Please upload an audio file."
    try:
        status = []
        progress(0.1, desc="Loading Audio...")
        y, sr = librosa.load(audio_path, sr=None)

        if do_trim:
            y, _ = librosa.effects.trim(y, top_db=30)
            status.append("✂️ Silences trimmed.")

        progress(0.3, desc="Applying FX...")
        if speed != 1.0:
            y = librosa.effects.time_stretch(y, rate=speed)
            status.append(f"⏱️ Speed changed to {speed}x.")

        if bgm_path:
            y = mix_background_music(y, sr, bgm_path, bgm_vol)
            status.append("🎵 Cinematic Background Music mixed in.")

        if do_norm:
            max_amp = np.max(np.abs(y))
            if max_amp > 0: y = y / max_amp * 0.95
            status.append("🔊 Volume normalized.")

        base_name = os.path.splitext(os.path.basename(audio_path))[0]
        out_folder = os.path.join(voice_folder, "Polished")
        os.makedirs(out_folder, exist_ok=True)

        temp_wav_path = os.path.join(out_folder, f"{base_name}_Polished.wav")
        sf.write(temp_wav_path, y, sr)

        files_to_download = []

        if do_srt:
            progress(0.7, desc="Generating SRT Captions...")
            status.append("📝 Generating precise SRT captions... please wait.")
            result = whisper_model.transcribe(temp_wav_path)
            srt_path = os.path.join(out_folder, f"{base_name}_Captions.srt")
            write_srt_file(result["segments"], srt_path)
            files_to_download.append(srt_path)
            status.append("✅ SRT generated successfully.")

        progress(0.9, desc="Converting Format...")
        final_export_path = convert_audio_format(temp_wav_path, out_format)
        files_to_download.insert(0, final_export_path)

        progress(1.0, desc="Done!")
        return final_export_path, files_to_download, "\n".join(status)
    except Exception as e:
        return None, None, f"❌ Error: {str(e)}"

# =========================================================================
# 💾 PRESET LOGIC
# =========================================================================
def load_presets():
    if os.path.exists(presets_file):
        with open(presets_file, "r") as f: return json.load(f)
    return {}

def save_preset_to_drive(name, desc, lang):
    name = name.strip()
    if not name: return gr.update(), "⚠️ Provide a preset name."
    presets = load_presets()
    presets[name] = {"desc": desc, "lang": lang}
    with open(presets_file, "w") as f: json.dump(presets, f)
    return gr.update(choices=list(presets.keys()), value=name), f"✅ Saved preset: {name}"

def apply_preset(name):
    presets = load_presets()
    if name in presets: return presets[name]["desc"], presets[name]["lang"]
    return "", "Auto"

def load_clone_presets():
    if os.path.exists(clone_presets_file):
        with open(clone_presets_file, "r") as f: return json.load(f)
    return {}

def save_clone_preset(name, audio_path, ref_text, lang):
    name = name.strip()
    if not name or not audio_path: return gr.update(), "⚠️ Need name and audio."
    safe_name = "".join(x for x in name if x.isalnum() or x in "._- ")
    ext = os.path.splitext(audio_path)[1] or ".wav"
    timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    permanent_audio_path = os.path.join(clone_audio_folder, f"{safe_name}_{timestamp}{ext}")
    shutil.copy(audio_path, permanent_audio_path)
    presets = load_clone_presets()
    presets[name] = {"audio_path": permanent_audio_path, "ref_text": ref_text if ref_text else "", "lang": lang}
    with open(clone_presets_file, "w") as f: json.dump(presets, f)
    return gr.update(choices=list(presets.keys()), value=name), f"✅ Saved: {name}"

def apply_clone_preset(name):
    presets = load_clone_presets()
    if name in presets: return presets[name]["audio_path"], presets[name]["ref_text"], presets[name]["lang"]
    return None, "", "Auto"

# =========================================================================
# 🎙️ GENERATION ENGINES (Master, Podcast, Batch)
# =========================================================================
def master_generate(text, lang, model_type, custom_filename, use_chunking, out_format, desc=None, ref_audio=None, ref_text=None, x_vector=False, do_norm=True, do_trim=True, do_srt=True, progress=None):
    try:
        if progress: progress(0.05, desc="Loading Model to VRAM...")
        switch_vram_model("design" if model_type == "design" else "base")

        custom_filename = custom_filename.strip()
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        base_name = custom_filename if custom_filename else f"Generated_{timestamp}"
        final_wav_name = f"{base_name}.wav"
        final_drive_path = os.path.join(voice_folder, final_wav_name)

        chunks_to_process = split_text_into_chunks(text) if use_chunking else [text]
        generated_audio_segments = []
        sample_rate = 24000

        for idx, chunk in enumerate(chunks_to_process):
            if not chunk.strip(): continue
            if progress: progress(0.1 + (0.6 * (idx / max(1, len(chunks_to_process)))), desc=f"Generating chunk {idx+1}/{len(chunks_to_process)}...")

            if model_type == "design":
                wavs, sr = model_design.generate_voice_design(text=chunk, language=lang, instruct=desc, non_streaming_mode=True)
            else:
                wavs, sr = model_base.generate_voice_clone(language=lang, text=chunk, ref_audio=ref_audio, ref_text=ref_text if not x_vector else None)
            sample_rate = sr
            generated_audio_segments.append(wavs[0].cpu().numpy() if torch.is_tensor(wavs[0]) else wavs[0])

        if generated_audio_segments:
            silence = np.zeros(int(0.3 * sample_rate), dtype=generated_audio_segments[0].dtype)
            final_audio_list = []
            for i, seg in enumerate(generated_audio_segments):
                final_audio_list.append(seg)
                if i < len(generated_audio_segments) - 1: final_audio_list.append(silence)
            sf.write(final_drive_path, np.concatenate(final_audio_list), sample_rate)

        downloads = []
        status_msg = f"✅ Audio generated successfully!"

        if do_norm or do_trim or do_srt:
            if progress: progress(0.8, desc="Applying Polish & Captions...")
            status_msg += "\n⚙️ Applying Polish & Captions..."
            y, sr_load = librosa.load(final_drive_path, sr=None)

            if do_trim:
                y, _ = librosa.effects.trim(y, top_db=30)
            if do_norm:
                max_amp = np.max(np.abs(y))
                if max_amp > 0: y = y / max_amp * 0.95
            if do_trim or do_norm:
                sf.write(final_drive_path, y, sr_load)
                status_msg += " (Audio Polished)"
            if do_srt:
                res = whisper_model.transcribe(final_drive_path)
                srt_path = final_drive_path.replace(".wav", ".srt")
                write_srt_file(res["segments"], srt_path)
                downloads.append(srt_path)
                status_msg += " (SRT Generated)"

        if progress: progress(0.95, desc="Converting Format...")
        final_export_path = convert_audio_format(final_drive_path, out_format)
        downloads.insert(0, final_export_path)

        status_msg += f"\n📂 Saved to Output Directory: {os.path.basename(final_export_path)}"

        if progress: progress(1.0, desc="Done!")
        return final_export_path, downloads, status_msg
    except Exception as e: return None, None, f"❌ Error: {str(e)}"

def btn_design_wrapper(txt, lng, fn, chunk, fmt, desc, norm, trim, srt, progress=gr.Progress()):
    return master_generate(txt, lng, "design", fn, chunk, fmt, desc=desc, do_norm=norm, do_trim=trim, do_srt=srt, progress=progress)

def btn_clone_wrapper(txt, lng, fn, chunk, fmt, ra, rt, xv, norm, trim, srt, progress=gr.Progress()):
    return master_generate(txt, lng, "clone", fn, chunk, fmt, ref_audio=ra, ref_text=rt, x_vector=xv, do_norm=norm, do_trim=trim, do_srt=srt, progress=progress)

def run_podcast_engine(script_text, lang, do_norm, do_trim, do_srt, out_format,
                       s1_n, s1_p, s1_audio, s1_ref,
                       s2_n, s2_p, s2_audio, s2_ref,
                       s3_n, s3_p, s3_audio, s3_ref,
                       s4_n, s4_p, s4_audio, s4_ref, progress=gr.Progress()):
    try:
        progress(0.05, desc="Loading Podcast Setup...")
        switch_vram_model("base")
        presets = load_clone_presets()

        # Build Speaker Mapping Dictionary
        speaker_map = {}

        def map_speaker(name, preset, audio, ref_text):
            name = name.strip()
            if not name: return

            if audio is not None:
                # Prioritize direct upload
                speaker_map[name] = {"type": "upload", "audio": audio, "ref_text": ref_text}
            elif preset:
                # Fallback to preset
                speaker_map[name] = {"type": "preset", "preset_name": preset}

        map_speaker(s1_n, s1_p, s1_audio, s1_ref)
        map_speaker(s2_n, s2_p, s2_audio, s2_ref)
        map_speaker(s3_n, s3_p, s3_audio, s3_ref)
        map_speaker(s4_n, s4_p, s4_audio, s4_ref)

        lines = script_text.split('\n')
        segments = []
        sr_final = 24000
        status_log = ["🎙️ Starting Podcast Generation..."]
        yield None, None, "\n".join(status_log)

        for i, line in enumerate(lines):
            line = line.strip()
            if not line: continue

            match = re.match(r'^\[(.*?)\]:\s*(.*)', line)
            if match:
                raw_speaker = match.group(1).strip()
                text = match.group(2).strip()

                if raw_speaker not in speaker_map:
                    if raw_speaker in presets:
                        speaker_info = {"type": "preset", "preset_name": raw_speaker}
                    else:
                        status_log.append(f"⚠️ Error: Speaker '{raw_speaker}' not mapped and not a known preset. Skipping line.")
                        yield None, None, "\n".join(status_log)
                        continue
                else:
                    speaker_info = speaker_map[raw_speaker]

                progress(0.1 + (0.7 * (i / max(1, len(lines)))), desc=f"Dubbing [{raw_speaker}]...")
                status_log.append(f"⏳ Generating audio for [{raw_speaker}]...")
                yield None, None, "\n".join(status_log)

                if speaker_info["type"] == "upload":
                    audio_path = speaker_info["audio"]
                    ref_text = speaker_info["ref_text"]
                else:
                    preset_name = speaker_info["preset_name"]
                    audio_path = presets[preset_name]["audio_path"]
                    ref_text = presets[preset_name]["ref_text"]

                wavs, sr = model_base.generate_voice_clone(language=lang, text=text, ref_audio=audio_path, ref_text=ref_text)
                sr_final = sr
                segments.append(wavs[0].cpu().numpy() if torch.is_tensor(wavs[0]) else wavs[0])

                silence = np.zeros(int(0.5 * sr_final), dtype=segments[-1].dtype)
                segments.append(silence)
            else:
                status_log.append(f"⚠️ Formatting ignored for line: {line[:20]}...")
                yield None, None, "\n".join(status_log)

        if not segments:
            yield None, None, "❌ No valid dialogue found. Ensure format is [Speaker]: Text"
            return

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        final_drive_path = os.path.join(voice_folder, f"Podcast_{timestamp}.wav")
        sf.write(final_drive_path, np.concatenate(segments), sr_final)

        downloads = []
        status_log.append(f"✅ Podcast generated successfully!")

        if do_norm or do_trim or do_srt:
            progress(0.85, desc="Final Mix & Captions...")
            status_log.append("⚙️ Applying Final Mix and Captions...")
            yield None, None, "\n".join(status_log)

            y, sr_load = librosa.load(final_drive_path, sr=None)
            if do_trim: y, _ = librosa.effects.trim(y, top_db=30)
            if do_norm:
                max_amp = np.max(np.abs(y))
                if max_amp > 0: y = y / max_amp * 0.95
            if do_trim or do_norm:
                sf.write(final_drive_path, y, sr_load)

            if do_srt:
                res = whisper_model.transcribe(final_drive_path)
                srt_path = final_drive_path.replace(".wav", ".srt")
                write_srt_file(res["segments"], srt_path)
                downloads.append(srt_path)
                status_log.append("✅ Master SRT Generated")

        progress(0.95, desc="Converting Format...")
        final_export_path = convert_audio_format(final_drive_path, out_format)
        downloads.insert(0, final_export_path)

        progress(1.0, desc="Podcast Ready!")
        yield final_export_path, downloads, "\n".join(status_log)

    except Exception as e:
        yield None, None, f"❌ Error: {str(e)}"

def run_batch(mode, text_list, lang, desc, clone_preset, custom_prefix, do_srt, target_langs, out_format, progress=gr.Progress()):
    try:
        progress(0.05, desc="Initializing Batch Engine...")
        switch_vram_model("design" if mode == "Voice Design" else "base")

        lines = [line.strip() for line in text_list.split('\n') if line.strip()]
        if not lines:
            yield None, "⚠️ Please paste some text."
            return

        prefix = custom_prefix.strip() if custom_prefix.strip() else "Batch"
        batch_folder = os.path.join(voice_folder, f"{prefix}_Batch_{datetime.datetime.now().strftime('%H%M%S')}")
        os.makedirs(batch_folder, exist_ok=True)

        audio_path, ref_text = None, None
        if mode == "Voice Clone":
            if not clone_preset:
                yield None, "⚠️ Please select a Clone Preset."
                return
            presets = load_clone_presets()
            audio_path, ref_text = presets[clone_preset]["audio_path"], presets[clone_preset]["ref_text"]

        lang_map = {
            "English": "en", "Chinese": "zh-CN", "Japanese": "ja",
            "Korean": "ko", "French": "fr", "German": "de", "Spanish": "es"
        }

        status_log = [f"🚀 Starting Batch: {len(lines)} scripts detected.\nFolder: {batch_folder}"]
        yield None, "\n".join(status_log)

        all_downloadable_files = []

        for i, line in enumerate(lines):
            progress((i+1)/len(lines), desc=f"Processing Base Audio {i+1}/{len(lines)}...")
            status_log.append(f"⏳ Processing {i+1}/{len(lines)}: {line[:30]}...")
            yield None, "\n".join(status_log)

            wav_filepath = os.path.join(batch_folder, f"{prefix}_{str(i+1).zfill(2)}_{lang}.wav")
            if mode == "Voice Design":
                wavs, sr = model_design.generate_voice_design(text=line, language=lang, instruct=desc, non_streaming_mode=True)
            else:
                wavs, sr = model_base.generate_voice_clone(language=lang, text=line, ref_audio=audio_path, ref_text=ref_text)

            sf.write(wav_filepath, wavs[0].cpu().numpy() if torch.is_tensor(wavs[0]) else wavs[0], sr)

            if do_srt:
                res = whisper_model.transcribe(wav_filepath)
                srt_path = wav_filepath.replace(".wav", ".srt")
                write_srt_file(res["segments"], srt_path)
                all_downloadable_files.append(srt_path)

            final_base_file = convert_audio_format(wav_filepath, out_format)
            all_downloadable_files.append(final_base_file)

            # TARGET LANGUAGES DUBBING
            for g_lang in target_langs:
                if g_lang == lang: continue
                code = lang_map.get(g_lang, "en")
                translated = GoogleTranslator(source='auto', target=code).translate(line)

                g_wav_filepath = os.path.join(batch_folder, f"{prefix}_{str(i+1).zfill(2)}_{g_lang}.wav")

                if mode == "Voice Design":
                    g_wavs, sr = model_design.generate_voice_design(text=translated, language=g_lang, instruct=desc, non_streaming_mode=True)
                else:
                    g_wavs, sr = model_base.generate_voice_clone(language=g_lang, text=translated, ref_audio=audio_path, ref_text=ref_text)

                sf.write(g_wav_filepath, g_wavs[0].cpu().numpy() if torch.is_tensor(g_wavs[0]) else g_wavs[0], sr)

                if do_srt:
                    g_res = whisper_model.transcribe(g_wav_filepath)
                    g_srt_path = g_wav_filepath.replace(".wav", ".srt")
                    write_srt_file(g_res["segments"], g_srt_path)
                    all_downloadable_files.append(g_srt_path)

                final_dub_file = convert_audio_format(g_wav_filepath, out_format)
                all_downloadable_files.append(final_dub_file)

        progress(1.0, desc="Batch Complete!")
        status_log.append(f"✅ Batch Complete! All files saved to: {batch_folder}")
        yield all_downloadable_files, "\n".join(status_log)

    except Exception as e:
        yield None, f"❌ Batch Error: {str(e)}"

# =========================================================================
# 🎨 BUILD THE UI
# =========================================================================
initial_presets = list(load_presets().keys())
initial_clone_presets = list(load_clone_presets().keys())

gr.close_all()

with gr.Blocks(theme=gr.themes.Default(primary_hue="indigo")) as app:

    # 🌟 CUSTOM YOUTUBE BRANDING BANNER 🌟
    gr.HTML("""
    <div style="text-align: center; margin-bottom: 20px;">
        <img src="https://github.com/TechTheoryLab/TechTheoryLab-Assets/blob/main/Tech%20Theory%20Lab%20Banner.png?raw=true"
             style="max-width: 100%; height: auto; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.2);">
        <br><br>
        <a href="https://www.youtube.com/@TechTheoryLab?sub_confirmation=1" target="_blank"
           style="display: inline-block; padding: 12px 24px; background-color: #ff0000; color: #ffffff; font-weight: bold; text-decoration: none; border-radius: 6px; font-size: 16px; transition: background-color 0.3s ease; box-shadow: 0 4px 10px rgba(255,0,0,0.4);">
            ▶️ SUBSCRIBE TO TECH THEORY LAB
        </a>
    </div>
    """)

    with gr.Row():
        clear_vram_btn = gr.Button("🧹 Clear GPU Memory (Fix Crashes)", variant="stop", scale=0)
        vram_status = gr.Textbox(label="", placeholder="System Status...", interactive=False, scale=1)

    clear_vram_btn.click(fn=manual_clear_vram, outputs=[vram_status])

    with gr.Tabs():

        # --- TAB 1: VOICE DESIGN ---
        with gr.Tab("Voice Design"):
            with gr.Row():
                # Left Column: Inputs & Settings
                with gr.Column(scale=1):
                    gr.Markdown("### 📝 Script & Settings")
                    vd_text = gr.Textbox(label="Script", lines=5)
                    with gr.Row():
                        vd_lang = gr.Dropdown(choices=QWEN_LANGUAGES, value="Auto", label="Language")
                        vd_filename = gr.Textbox(label="File Name", placeholder="Optional")

                    vd_desc = gr.Textbox(label="Voice Description", lines=2, placeholder="e.g., A confident female news anchor speaking clearly.")

                    with gr.Group():
                        gr.Markdown("⚙️ **Processing Options**")
                        with gr.Row():
                            vd_chunking = gr.Checkbox(label="🔪 Auto-Chunking", value=False)
                            vd_norm = gr.Checkbox(label="🔊 Auto-Normalize", value=True)
                        with gr.Row():
                            vd_trim = gr.Checkbox(label="✂️ Auto-Trim", value=True)
                            vd_srt = gr.Checkbox(label="📝 Generate .SRT", value=True)

                    vd_format = gr.Dropdown(choices=["WAV", "MP3", "FLAC", "OGG"], value="MP3", label="Output Format")
                    vd_btn = gr.Button("✨ Generate Polished Audio", variant="primary", size="lg")

                # Right Column: Presets & Outputs
                with gr.Column(scale=1):
                    with gr.Group():
                        gr.Markdown("### 💾 Presets Management")
                        with gr.Row(equal_height=True):
                            vd_preset_dropdown = gr.Dropdown(choices=initial_presets, label="Load Saved Voice Preset", scale=2)
                            vd_preset_name = gr.Textbox(label="New Preset Name", scale=2)
                        vd_save_preset_btn = gr.Button("💾 Save Current Configuration as Preset")

                    gr.Markdown("### 🎧 Output Dashboard")
                    vd_audio = gr.Audio(label="Audio Output")
                    vd_download = gr.File(label="📥 Download Files", file_count="multiple", interactive=False)
                    vd_status = gr.Textbox(label="Status Console", lines=3)

            # Wiring
            vd_preset_dropdown.change(fn=apply_preset, inputs=[vd_preset_dropdown], outputs=[vd_desc, vd_lang])
            vd_save_preset_btn.click(fn=save_preset_to_drive, inputs=[vd_preset_name, vd_desc, vd_lang], outputs=[vd_preset_dropdown, vd_status])
            vd_btn.click(fn=btn_design_wrapper, inputs=[vd_text, vd_lang, vd_filename, vd_chunking, vd_format, vd_desc, vd_norm, vd_trim, vd_srt], outputs=[vd_audio, vd_download, vd_status])

        # --- TAB 2: VOICE CLONE ---
        with gr.Tab("Voice Clone"):
            with gr.Row():
                # Left Column: Inputs & Settings
                with gr.Column(scale=1):
                    gr.Markdown("### 🎤 Source Audio & Target Script")
                    vc_ref_audio = gr.Audio(type="filepath", label="Reference Audio")
                    vc_ref_text = gr.Textbox(label="Reference Transcript (Optional)", lines=2)
                    vc_xvector = gr.Checkbox(label="Ignore Transcript (x-vector mode only)")

                    vc_target_text = gr.Textbox(label="Target Script to Clone", lines=4)

                    with gr.Row():
                        vc_lang = gr.Dropdown(choices=QWEN_LANGUAGES, value="Auto", label="Language")
                        vc_filename = gr.Textbox(label="File Name", placeholder="Optional")

                    with gr.Group():
                        gr.Markdown("⚙️ **Processing Options**")
                        with gr.Row():
                            vc_chunking = gr.Checkbox(label="🔪 Auto-Chunking", value=False)
                            vc_norm = gr.Checkbox(label="🔊 Auto-Normalize", value=True)
                        with gr.Row():
                            vc_trim = gr.Checkbox(label="✂️ Auto-Trim", value=True)
                            vc_srt = gr.Checkbox(label="📝 Generate .SRT", value=True)

                    vc_format = gr.Dropdown(choices=["WAV", "MP3", "FLAC", "OGG"], value="MP3", label="Output Format")
                    vc_btn = gr.Button("🧬 Clone Voice & Generate Audio", variant="primary", size="lg")

                # Right Column: Presets & Outputs
                with gr.Column(scale=1):
                    with gr.Group():
                        gr.Markdown("### 💾 Clone Presets Management")
                        with gr.Row(equal_height=True):
                            vc_preset_dropdown = gr.Dropdown(choices=initial_clone_presets, label="Load Preset", scale=2)
                            vc_preset_name = gr.Textbox(label="New Preset Name", placeholder="e.g. Creator_Main", scale=2)
                        vc_save_preset_btn = gr.Button("💾 Save Current Voice as Preset")

                    gr.Markdown("### 🎧 Output Dashboard")
                    vc_audio = gr.Audio(label="Audio Output")
                    vc_download = gr.File(label="📥 Download Files", file_count="multiple", interactive=False)
                    vc_status = gr.Textbox(label="Status Console", lines=3)

            # Wiring
            vc_preset_dropdown.change(fn=apply_clone_preset, inputs=[vc_preset_dropdown], outputs=[vc_ref_audio, vc_ref_text, vc_lang])
            vc_save_preset_btn.click(fn=save_clone_preset, inputs=[vc_preset_name, vc_ref_audio, vc_ref_text, vc_lang], outputs=[vc_preset_dropdown, vc_status])
            vc_btn.click(fn=btn_clone_wrapper, inputs=[vc_target_text, vc_lang, vc_filename, vc_chunking, vc_format, vc_ref_audio, vc_ref_text, vc_xvector, vc_norm, vc_trim, vc_srt], outputs=[vc_audio, vc_download, vc_status])

        # --- TAB 3: VIRAL BATCH GENERATOR ---
        with gr.Tab("Batch Generator"):
            with gr.Row():
                # Left Column: Setup
                with gr.Column(scale=1):
                    gr.Markdown("### 🚀 Multi-Script Batch Processing")
                    batch_mode = gr.Radio(choices=["Voice Design", "Voice Clone"], value="Voice Clone", label="Generation Mode")
                    batch_text = gr.Textbox(label="Paste multiple scripts (Press Enter between each to create separate files)", lines=6)

                    with gr.Group(visible=False) as design_row:
                        batch_desc = gr.Textbox(label="Voice Description", lines=2)
                    with gr.Group(visible=True) as clone_row:
                        batch_clone_preset = gr.Dropdown(choices=initial_clone_presets, label="Select Voice Clone Preset")

                    with gr.Row():
                        batch_lang = gr.Dropdown(choices=QWEN_LANGUAGES, value="Auto", label="Base Language")
                        batch_prefix = gr.Textbox(label="File Prefix", placeholder="e.g., Tech_Shorts")

                # Right Column: Export & Localization
                with gr.Column(scale=1):
                    with gr.Group():
                        gr.Markdown("### 🌍 Global Localization Studio")
                        batch_target_langs = gr.CheckboxGroup(
                            choices=["English", "Chinese", "Japanese", "Korean", "French", "German", "Spanish"],
                            label="Select Languages for Auto-Dubbing (Translates & Generates additional files!)"
                        )

                    with gr.Group():
                        gr.Markdown("### ⚙️ Output Settings")
                        batch_srt = gr.Checkbox(label="📝 Auto-Generate .SRT Captions for EVERY file", value=True)
                        batch_format = gr.Dropdown(choices=["WAV", "MP3", "FLAC", "OGG"], value="MP3", label="Output Format")

                    batch_btn = gr.Button("⚡ Run Super-Batch Processing", variant="primary", size="lg")
                    batch_downloads = gr.File(label="📥 Download Generated Batch Archive", interactive=False)
                    batch_status = gr.Textbox(label="Batch Status Log", interactive=False, lines=4)

            # Wiring
            def toggle_batch_mode(mode): return (gr.update(visible=True), gr.update(visible=False)) if mode == "Voice Design" else (gr.update(visible=False), gr.update(visible=True))
            batch_mode.change(fn=toggle_batch_mode, inputs=[batch_mode], outputs=[design_row, clone_row])
            batch_btn.click(fn=run_batch, inputs=[batch_mode, batch_text, batch_lang, batch_desc, batch_clone_preset, batch_prefix, batch_srt, batch_target_langs, batch_format], outputs=[batch_downloads, batch_status])

        # --- TAB 4: PODCAST STUDIO ---
        with gr.Tab("Podcast Studio"):
            gr.Markdown("### 🎙️ Multi-Speaker Dialogue Editor")
            gr.Markdown("Type your script using character names: `[Host]: Welcome!` or `[Guest]: Hello!`. Map the names to a saved preset **OR** upload an audio file directly below. *(Uploads override presets).*")

            with gr.Row():
                # Left Column: Speaker Mapping
                with gr.Column(scale=1):
                    with gr.Accordion("👥 Cast Members (Presets OR Direct Uploads)", open=True):
                        # Speaker 1
                        with gr.Group():
                            with gr.Row(equal_height=True):
                                s1_name = gr.Textbox(label="Speaker 1 Tag (e.g., Host)", scale=1)
                                s1_preset = gr.Dropdown(choices=initial_clone_presets, label="Preset", scale=1)
                            with gr.Row(equal_height=True):
                                s1_audio = gr.Audio(type="filepath", label="OR Direct Audio", scale=1)
                                s1_ref = gr.Textbox(label="Ref Text (Opt)", lines=1, scale=1)
                        # Speaker 2
                        with gr.Group():
                            with gr.Row(equal_height=True):
                                s2_name = gr.Textbox(label="Speaker 2 Tag (e.g., Guest)", scale=1)
                                s2_preset = gr.Dropdown(choices=initial_clone_presets, label="Preset", scale=1)
                            with gr.Row(equal_height=True):
                                s2_audio = gr.Audio(type="filepath", label="OR Direct Audio", scale=1)
                                s2_ref = gr.Textbox(label="Ref Text (Opt)", lines=1, scale=1)
                        # Speaker 3
                        with gr.Accordion("Expand for Speakers 3 & 4", open=False):
                            with gr.Group():
                                with gr.Row(equal_height=True):
                                    s3_name = gr.Textbox(label="Speaker 3 Tag", scale=1)
                                    s3_preset = gr.Dropdown(choices=initial_clone_presets, label="Preset", scale=1)
                                with gr.Row(equal_height=True):
                                    s3_audio = gr.Audio(type="filepath", label="OR Direct Audio", scale=1)
                                    s3_ref = gr.Textbox(label="Ref Text (Opt)", lines=1, scale=1)
                            # Speaker 4
                            with gr.Group():
                                with gr.Row(equal_height=True):
                                    s4_name = gr.Textbox(label="Speaker 4 Tag", scale=1)
                                    s4_preset = gr.Dropdown(choices=initial_clone_presets, label="Preset", scale=1)
                                with gr.Row(equal_height=True):
                                    s4_audio = gr.Audio(type="filepath", label="OR Direct Audio", scale=1)
                                    s4_ref = gr.Textbox(label="Ref Text (Opt)", lines=1, scale=1)

                # Right Column: Script & Output
                with gr.Column(scale=1):
                    pod_script = gr.Textbox(label="Master Podcast Script", lines=12, placeholder="[Host]: Welcome back to the show!\n[Guest]: Thanks for having me.")

                    with gr.Group():
                        gr.Markdown("⚙️ **Master Export Settings**")
                        with gr.Row():
                            pod_lang = gr.Dropdown(choices=QWEN_LANGUAGES, value="Auto", label="Master Language")
                            pod_format = gr.Dropdown(choices=["WAV", "MP3", "FLAC", "OGG"], value="MP3", label="Format")
                        with gr.Row():
                            pod_norm = gr.Checkbox(label="🔊 Normalize Master", value=True)
                            pod_trim = gr.Checkbox(label="✂️ Trim Master", value=True)
                            pod_srt = gr.Checkbox(label="📝 Generate Master .SRT", value=True)

                    pod_btn = gr.Button("🎧 Compile Full Episode", variant="primary", size="lg")
                    pod_audio = gr.Audio(label="Master Podcast Output")
                    pod_download = gr.File(label="📥 Download Assets", file_count="multiple", interactive=False)
                    pod_status = gr.Textbox(label="Podcast Console Log", lines=4)

            # Wiring
            pod_btn.click(
                fn=run_podcast_engine,
                inputs=[
                    pod_script, pod_lang, pod_norm, pod_trim, pod_srt, pod_format,
                    s1_name, s1_preset, s1_audio, s1_ref,
                    s2_name, s2_preset, s2_audio, s2_ref,
                    s3_name, s3_preset, s3_audio, s3_ref,
                    s4_name, s4_preset, s4_audio, s4_ref
                ],
                outputs=[pod_audio, pod_download, pod_status]
            )

        # --- TAB 5: POST-PROCESSING & FX MIXER ---
        with gr.Tab("FX Mixer"):
            with gr.Row():
                # Left Column: Inputs & FX
                with gr.Column(scale=1):
                    gr.Markdown("### 🎛️ Audio Input & Effects")
                    pp_audio_in = gr.Audio(type="filepath", label="1. Upload Voice Audio (.wav)")

                    with gr.Group():
                        gr.Markdown("🎵 **Background Music Track**")
                        pp_bgm_in = gr.Audio(type="filepath", label="2. Upload Background Music (Optional)")
                        pp_bgm_vol = gr.Slider(minimum=0.0, maximum=1.0, value=0.15, step=0.05, label="BGM Volume")

                    with gr.Group():
                        gr.Markdown("🎚️ **Mastering Tools**")
                        with gr.Row():
                            pp_norm = gr.Checkbox(label="🔊 Normalize Volume", value=True)
                            pp_trim = gr.Checkbox(label="✂️ Trim Dead Air", value=True)
                            pp_srt = gr.Checkbox(label="📝 Generate .SRT", value=True)
                        pp_speed = gr.Slider(minimum=0.8, maximum=1.5, value=1.0, step=0.05, label="⏱️ Speed Adjust")

                    pp_format = gr.Dropdown(choices=["WAV", "MP3", "FLAC", "OGG"], value="MP3", label="Final Output Format")
                    pp_btn = gr.Button("⚡ Apply FX & Mix", variant="primary", size="lg")

                # Right Column: Output
                with gr.Column(scale=1):
                    gr.Markdown("### 🎧 Master Output Dashboard")
                    pp_audio_out = gr.Audio(label="Final Mixed Audio")
                    pp_downloads = gr.File(label="📥 Download Mastered Files", file_count="multiple", interactive=False)
                    pp_status = gr.Textbox(label="Mixer Console Log", lines=8)

            # Wiring
            pp_btn.click(fn=process_audio_studio, inputs=[pp_audio_in, pp_norm, pp_trim, pp_speed, pp_srt, pp_bgm_in, pp_bgm_vol, pp_format], outputs=[pp_audio_out, pp_downloads, pp_status])

print("Starting Tech Theory Lab Pro Studio...")
app.launch(inline=True, share=True, debug=True, show_error=True)
